#!/usr/bin/ruby
require 'rubygems'
require 'active_support'
require 'pp'
require 'pathname'
require 'yaml'
require File.dirname(__FILE__) + '/../lib/fixture_converter'

path = Pathname.new(ARGV[0])

fc = FixtureConverter.new
if path.file?
  fc.convert_fixture(path)
else
  fc.convert_scenario(path)
end
fc.out

